<?xml version="1.0" encoding="UTF-8"?> 
<!-- DTD for properties --> 
<!DOCTYPE properties [
    <!ELEMENT properties ( comment?, property* ) >
    <!ATTLIST properties version CDATA #FIXED "1.0">
    <!ELEMENT comment (#PCDATA) >
    <!ELEMENT property (#PCDATA) >
    <!ATTLIST property key CDATA #REQUIRED>
]>
<properties>
	<property key="UPLOAD_DIR">D:/upload/aisou</property>
	<property key="UPLOAD_TABLE">BS_UPLOAD</property>
	<property key="UPLOAD_DIR_DATE_FORMAT">yyyyMM</property>
	<property key="FILE_SERVER">http://img.dssh.tv</property>
</properties>